### ISSUE TITLE
Stopped working Fedora 40.

### ISSUE THREAD

**Issue by Plyply99** [sereneblue/gnome-shell-extension-krypto#18]
It worked fine couple days ago but now it only shows "...Loading"  for a second and then nothing.

**Comment by Plyply99** [comment]
Update:
Was reading news and it started working. I did nothing lol.
Anyway thank you for this great extension!

**Comment by sereneblue** [comment]
Hi @Plyply99,

> It worked fine couple days ago but now it only shows "...Loading" for a second and then nothing.

This can happen if there was a network error or an issue with the request. I'd need to check if this would break the extension until next login or if it'll resume the next time it tries to update.

EDIT: If there's an error, it won't update the top bar, however, it'll keep trying at the interval specified in your settings.
