### ISSUE TITLE
Suggestion: allow to choose what currencies are being displayed in the top bar.

### ISSUE THREAD

**Issue by lig** [sereneblue/gnome-shell-extension-krypto#8]
The current behavior is to show N (configurable) number of currencies from the list of enabled currencies.

This actually means to show N first currencies in alphabetic order.

It would be great to be able to choose the exact list of currencies to be displayed in the top bar.

I suggest adding a checkbox to each entry in the list of enabled currencies that will set this specific currency to be displayed in the top bar.

**Example**

Enabled currencies:
- Binance Coin
- Bitcoin
- Decred
- Etherium

Desired currencies to be displayed in the top bar:
- Bitcoin
- Etherium

The current behavior is to set N to 4 and observe the following list:
- Binance Coin
- Bitcoin
- Decred
- Etherium

The suggested behavior is to tick checkboxes for corresponding currencies and observe the following list of currencies in the top bar:
- Bitcoin
- Etherium

**Comment by lig** [comment]
I think it is safe to make this checkbox enabled by default.

**Comment by sereneblue** [comment]
Hi @lig,

Thanks for the suggestion. I'll take a look at implementing this change in the next update.

**Comment by sereneblue** [comment]
@lig This functionality is introduced in v15.

**Comment by lig** [comment]
Thanks! It works.
I'd say the UX could be better but it's good enough:)
Keep up the great work!
